Task/tp 1015 custom module technical run through
City-of-Helsinki/drupal-helfi-tyollisyyspalvelut-manuaali pull request #454
Opened 2023-09-20 05:47 UTC by jussiviitamaki

**Actions necessary for applying the changes:** *(for example composer install; drush updb; drush cim)*

**Testing instructions:**
- [ ] Login and create content
- [ ] Check the content

**Review checklist:**
- [ ] The code conforms to Drupal coding standards
- [ ] I have reviewed the code for security and quality issues
- [ ] I have tested the code with the proper **user** roles
- [ ] I have moved the ticket to the approval lane, added testing instructions and assigned it to the product owner.

2023-09-25 11:32 UTC, tapsal requested changes
I think search suggestions are broken as they seem to show the escaped HTML.

2023-09-29 09:44 UTC, tapsal approved these changes

2023-10-02 10:16 UTC, IiroJarv approved these changes

2023-10-02 11:36 UTC, tapsal approved these changes

2023-10-02 11:57 UTC, merged